# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

before_all do
  # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  # sh "./customShellScript.sh"

  cocoapods
  xctool :'build-tests'
end

lane :test do
  xctool :'run-tests'
end

lane :beta do
  # snapshot
  # sigh
  # increment_build_number
  ipa({
    workspace: ENV["WORKSPACE"],
    configuration: ENV["DEBUG"],
    scheme: ENV["SCHEME"],
  })
  deliver :skip_deploy, :beta
  # sh "your_script.sh"
end

lane :deploy do
  # snapshot
  # sigh
  # increment_build_number
  ipa({
    workspace: ENV["WORKSPACE"],
    configuration: ENV["RELEASE"],
    scheme: ENV["SCHEME"],
  })
  deliver :skip_deploy, :force
  # frameit
end

lane :inhouse do
  # insert your code here
end

# You can define as many lanes as you want

after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end
