# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Find' do

end

target 'FindTests', :exclusive => true do
	pod 'Quick', :configurations => ['Debug']
	pod 'Nimble', :configurations => ['Debug']
end

target 'FindFunctionalTests', :exclusive => true do
 	 pod 'KIF', :configurations => ['Debug']
end
