# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Find' do

end

target 'FindTests', :exclusive => true do
	pod 'Quick', '~> 0.2', :configurations => ['Debug']
	pod 'Nimble', :configurations => ['Debug']
end
