# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Find' do

end

target 'FindTests' do
	pod 'Quick', '~> 0.2'
end

target 'FindFunctionalTests' do
	pod 'KIF-Kiwi', '~> 0.2'
end

